language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
install:
    - pip install -r .travis_requirements.txt
script:
    - pytest